param([switch]$SkipTests, [switch]$SkipInstaller, [switch]$SkipBuild)
# AC Mod Hub 2.0 — full release build (Windows + .NET 8 SDK + Inno Setup 6 required).
# Version comes from Directory.Build.props (single source of truth) and is injected
# into installer/version.iss so the installer can never drift from the assembly version.
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$publish = Join-Path $root 'artifacts\publish\win-x64'
$installer = Join-Path $root 'artifacts\installer'
Remove-Item $installer -Recurse -Force -ErrorAction SilentlyContinue

if (-not $SkipBuild) {
    Remove-Item $publish -Recurse -Force -ErrorAction SilentlyContinue

    # 1. Restore / build / test
    dotnet restore (Join-Path $root 'ACModHub.sln')
    dotnet build (Join-Path $root 'ACModHub.sln') -c Release --no-restore
    if (-not $SkipTests) { dotnet test (Join-Path $root 'ACModHub.sln') -c Release --no-build }

    # 2. Publish self-contained win-x64
    dotnet publish (Join-Path $root 'src\ACModHub.App\ACModHub.App.csproj') -c Release -r win-x64 --self-contained true --no-restore -o $publish
}

# 3. Portable package
$portable = Join-Path $root 'artifacts\AC-Mod-Hub-Portable-win-x64.zip'
Compress-Archive -Path "$publish\*" -DestinationPath $portable -Force

if (-not $SkipInstaller) {
    # 4. Installer (version injected from the single source)
    $version = Select-Xml -Path (Join-Path $root 'Directory.Build.props') -XPath "//*[local-name()='Version']" | Select-Object -First 1 -ExpandProperty Node
    $versionText = $version.InnerText
    "// Generated by build.ps1 from Directory.Build.props — do not edit manually.`n#define MyAppVersion `"$versionText`"" | Set-Content -Path (Join-Path $root 'installer\version.iss') -Encoding ASCII

    $iscc = @("${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe", "$env:ProgramFiles\Inno Setup 6\ISCC.exe") | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $iscc) { throw 'Inno Setup 6 was not found. Install it from https://jrsoftware.org/isinfo.php' }
    & $iscc "/DPublishDir=$publish" (Join-Path $root 'installer\ACModHub.iss')

    # 5. Checksums + release manifest
    $setup = Join-Path $installer 'AC-Mod-Hub-Setup.exe'
    $hash = (Get-FileHash -Algorithm SHA256 $setup).Hash.ToLowerInvariant()
    "$hash *AC-Mod-Hub-Setup.exe" | Set-Content -Path (Join-Path $installer 'SHA256SUMS.txt') -Encoding ASCII
    @"
Build info
==========
Version : $versionText
Source  : $(git rev-parse --short HEAD)
Date    : $(Get-Date -Format u)
"@ | Set-Content -Path (Join-Path $installer 'BUILD-INFO.txt') -Encoding UTF8
}

Write-Host "Portable : $portable"
Write-Host "Installer: $(Join-Path $installer 'AC-Mod-Hub-Setup.exe')"
Write-Host "Checksums: $(Join-Path $installer 'SHA256SUMS.txt')"
